### ISSUE TITLE
Contao Content Elemente mit Custom Elemente erweitern

### ISSUE THREAD

**Issue by fkaminski** [madeyourday/contao-rocksolid-custom-elements#100]
Ist es möglich ein bestehendes Custom Element in alle oder ein spezielles Contao Content Element z.B. ce_text einzufügen?

**Comment by ausi** [comment]
Für allgemeine Fragen zur Erweiterung bitte direkt an <https://my.rocksolidthemes.com/support> oder <https://community.contao.org/> wenden.

**Comment by fkaminski** [comment]
Ok, danke
