### ISSUE TITLE
Add Support for frontend form fields

### ISSUE THREAD

**Issue by ausi** [madeyourday/contao-rocksolid-custom-elements#102]
See <http://help.rocksolidthemes.com/discussions/contao/7512#comment_45833952>

```php
protected $blnSubmitInput = true;
public function validate()
{
	$varValue = $this->validator($this->getPost($this->strName));
	if ($this->hasErrors())
	{
		$this->class = 'error';
	}
	$this->varValue = $varValue;
}
```

**Comment by danielwolf1** [comment]
Thanks for starting this enhancement. Please note: I think we need some sort of check if the label and name field is set - otherwise empty values get submitted in emails, too.

**Comment by ausi** [comment]
Implemented in version 2.2.8.

Now every element that has a field like `'name' => ['inputType' => 'standardField']` can be used to submit form data.

**Comment by danielwolf1** [comment]
Am I guessing right, that this won't work:

'subscribe' => array(
			'inputType' => 'checkbox',
			'label' => array(
				'de' => array(
					'Zum Newsletter anmelden'
				)
			)
		),

**Comment by ausi** [comment]
For questions about the custom elements extension please refer to your support forum: <https://help.rocksolidthemes.com/discussions/contao/7512>
