### ISSUE TITLE
Exported themes misses rsce_*.php Files

### ISSUE THREAD

**Issue by taleteller** [madeyourday/contao-rocksolid-custom-elements#104]
I am using base themes containing RSCE. Sometimes I port such a theme to a new installation using theme export / import. However the contao/core only exports the html5 files from the templates folder, the also required php files are missing from the .cto archive. Therefore the elements wont appear in the list. 

I saw RSCE has a hook in the export routine to include "rsce_data" fields, would it be possible to add the missing php files to the export list as well?

**Comment by ausi** [comment]
Please add `php` to *System › Settings › Files and images › Template file types*, does this fix your issue?
