### ISSUE TITLE
Unspezifische Fehlermeldung bei Nutzung des Zugriffsschutzes

### ISSUE THREAD

**Issue by NinaG** [madeyourday/contao-rocksolid-custom-elements#105]
Ich habe ein Custom Element im Einsatz. Wenn ich darin unter Zugriffsschutz einstelle, dass nur einem bestimmte Mitgliedergruppe das Element sehen darf, speichert Contao zwar scheinbar diese Auswahl, zeigt aber ganz oben in der Elementansicht die unspezifische Meldung "Ein Fehler ist aufgetreten!". 

**Die Sache ist beliebig für mich reproduzierbar:** 
Ich lösche einfach den Haken wieder, speichere - alles in Ordnung, kein Fehler. 
Ich setze wieder den Haken bei "Zugriffsschutz" und der spezifischen Mitgliedergruppe, speichere - die Haken bleiben gesetzt, aber oben wird in Contao die Meldung "Ein Fehler ist aufgetreten!" angezeigt.

In var/logs finde ich dazu aber keinen Eintrag.

Ich nutze die aktuellste Version der Extension (gerade zur Sicherheit nochmal vorher aktualisiert). Eine Idee, was da passiert bzw. wie ich herausfinden könnte, welcher Fehler aufgetreten ist?

**Comment by ausi** [comment]
Vielen Dank für die detaillierte Fehlerbeschreibung!

Behoben in Version 2.2.7 🎉

**Comment by NinaG** [comment]
Danke und vielen Dank für die schnelle Reaktion :)
