### ISSUE TITLE
A possibility to configure the picker for an existent content element for using in a custom template

### ISSUE THREAD

**Issue by alorotom** [madeyourday/contao-rocksolid-custom-elements#108]
Hello!

No possibility to configure the picker for an existent content element for using in a custom template. Could you please implement this feature or explain how to use it?

Regards,
Alexander.

**Comment by ausi** [comment]
For general questions regarding the extension please contact the RockSolid Themes support at <https://my.rocksolidthemes.com/support> or refer to the Contao community forum <https://community.contao.org/>

**Comment by alorotom** [comment]
Thanks. Continued here: http://help.rocksolidthemes.com/discussions/contao/36260
