### ISSUE TITLE
Content element 'Gallery' - images order

### ISSUE THREAD

**Issue by godzik** [madeyourday/contao-rocksolid-custom-elements#109]
Hallo!
I'm trying to implement gallery-element. In general all good, but it seems like 'orderField'=>'orderSRC', doesnt work in rsce?
I can reorder images in settings, but on save it gets back to default order. What am i doing wrong?
My field config

```php
'gallery' => array(
	'label' => array('Bild (gallery carousel)', ''),
	'inputType' => 'fileTree',
	'eval' => array(
		'multiple' => true,
		'isGallery' => true,
		'tl_class' => 'clr autoheight',
		'fieldType' => 'checkbox',
		'filesOnly' => true,
		'orderField'=>'orderSRC',
		'extensions' => \Config::get('validImageTypes'),
	),
	'load_callback' => array 
	( 
		array('tl_content', 'setMultiSrcFlags') 
	) 
),
```

**Comment by ausi** [comment]
I was not able to reproduce the issue, your configuration worked in my test. I changed the order of the images in the backend and clicked on the save button and the order stayed as expected.

**Comment by godzik** [comment]
@ausi weird, i just tested in incognito mode - not working for me and for client. I cant save the order on first save or save-reorder-resave.
Also i've found this tread http://help.rocksolidthemes.com/discussions/contao/18654-usage-sort-order-on-filetree-element
is this true?

**Comment by ausi** [comment]
It is true that you cannot store the order in a “virtual” field, but if you are using an existing field from `tl_content` — like you did with `orderSRC` — it should be working.

Can you post the complete configuration of your element?

**Comment by godzik** [comment]
`<?php
return array(
	'label' => array(
		'de' => array(
            'Teaser | Slider (content width)'
        ),
        'en' => array(
            'Teaser | Slider (content width)'
        ),
	),
	'types' => array('content'),
  	'contentCategory' => 'Tor - Custom',
	'standardFields' => array('cssID'),
	'fields' => array(
		'teasers' => array(
			'label' => array('Teaser', ''),
			'elementLabel' => 'Teaser %s',
			'inputType' => 'list',
			'minItems' => 1,
			'maxItems' => 10,
			'fields' => array(
				'text' => array(
					'label' => array('Beschreibung', ''),
					'inputType' => 'textarea',
					'eval' => array('rte' => 'tinyMCE','tl_class' => 'clr w50'),
				),
                'headline' => array(
                    'label' => array('Headline', ''),
                    'inputType' => 'text',
                    'eval' => array('tl_class' => 'w50'),
                ),
                'headlineType' => array(
                    'label' => array('Headline Type', 'h1, h2,h3...'),
                    'inputType' => 'select',
                    'options' => array(
                        'h1' => 'H1',
                        'h2' => 'H2',
                        'h3' => 'H3',
                        'h4' => 'H4',
                        'h5' => 'H5',
                        'h6' => 'H6',
                    ),
                    'eval' => array('tl_class' => 'w50'),
                ),
				'label' => array(
					'label' => array('Link-Bezeichnung', ''),
					'inputType' => 'text',
					'eval' => array('tl_class' => 'w50'),
				),
				'url' => array(
					'label' => array('Link-URL', 'Beispiele: http://example.com, {{link_url::seitenalias}} (Alias, ID oder anderer Inserttag)'),
					'inputType' => 'url',
					'eval' => array('tl_class' => 'w50 wizard'),
				),
				'newWindow' => array(
					'label' => $GLOBALS['TL_LANG']['MSC']['target'],
					'inputType' => 'checkbox',
					'eval' => array('tl_class' => 'w50'),
				),
				'gallery' => array(
					'label' => array('Bild (gallery carousel)', ''),
					'inputType' => 'fileTree',
					'eval' => array(
						'multiple' => true,
						'isGallery' => true,
						'tl_class' => 'clr autoheight',
						'fieldType' => 'checkbox',
						'filesOnly' => true,
						'orderField'=>'orderSRC',
						'extensions' => \Config::get('validImageTypes'),
					),
					'load_callback' => array 
					( 
						array('tl_content', 'setMultiSrcFlags') 
					) 
				)
			),
		),
	),
);`

**Comment by ausi** [comment]
This is not possible inside of `'inputType' => 'list'` elements. You are currently using the same database column `orderSRC` for multiple fields which makes one field overwriting the other.

**Comment by godzik** [comment]
@ausi ah, ok, got it and ty for support. Will extend core gallery element then for my needs.
