### ISSUE TITLE
Gleiche Dateinamen in unterschiedlichen Template-Ordnern

### ISSUE THREAD

**Issue by thepixture** [madeyourday/contao-rocksolid-custom-elements#111]
Wir haben eine Multidomain-Installation, in der wir für jede Domain ein eigenes Theme mit eigenen Template-Ordner angelegt haben.
In beiden Template-Ordnern befinden sich teils gleiche Custom Elements mit individuellen Anpassungen. Die Elemente haben den gleichen Dateinamen.
Leider werden Elemente mit gleichen Dateinamen in unterschiedlichen Template-Ordnern von der Erweiterung nicht als individuelle Elemente behandelt, sondern es wird jeweils nur eines der beiden Elemente angezeigt. Eine Differenzierung über den Template-Ordner scheint hier nicht zu greifen.

**Comment by ausi** [comment]
Der Dateiname der Custom Elements muss einzigartig sein, eine Differenzierung über den Template-Ordner ist nicht möglich. Weitere Fragen zur Erweiterung können direkt an den Support gestellt werden: <https://my.rocksolidthemes.com/support>
