### ISSUE TITLE
Storing the RSCE templates in more than one folder causes issues

### ISSUE THREAD

**Issue by Defcon0** [madeyourday/contao-rocksolid-custom-elements#113]
Hello,

we stored our RSCE templates in subfolders for each domain we have, i.e.

vendor/acme/contao-my-bundle/src/Resources/contao/templates/domain1/elements
vendor/acme/contao-my-bundle/src/Resources/contao/templates/domain2/elements

This causes strange issues:

![screen](https://user-images.githubusercontent.com/1485098/64163362-68ebf100-ce41-11e9-92e9-b93262fde333.png)

When moving all templates to one folder, i.e.

vendor/acme/contao-my-bundle/src/Resources/contao/templates/common/elements

everything works just fine.

Maybe there's a bug?

Bye Defcon0

**Comment by ausi** [comment]
Should be fixed in the master branch.

Please verify if the fix works for your use case.
