### ISSUE TITLE
Warnings during initial install

### ISSUE THREAD

**Issue by m-vo** [madeyourday/contao-rocksolid-custom-elements#114]
When initially installing a project this happens when Contao's `post-update-cmd` is executed: 

`CustomElements::loadConfig()` tries to write a file with path `var/cache/prod/contao/rocksolid_custom_elements_config.php` here:
https://github.com/madeyourday/contao-rocksolid-custom-elements/blob/2072a904050462aff2f7a4da071d0a2f3ba96ada/src/CustomElements.php#L1301-L1303

`File->fputs()` however checks for `\is_resource($this->resFile)` and - because no handle exists  - tries write into `'system/tmp/' . md5(uniqid(mt_rand(), true))`. This early during install `system/tmp` does not exist yet. and therefore a warning is generated / the write fails.

> PHP Warning:  fopen(/path/to/project/system/tmp/d027baa80c3ff4241a870c03551b6c33): failed to open stream: No such file or directory in /path/to/project/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Files.php on line 159

maybe related #77 

Disclaimer: I didn't dig deeper yet whether it's right that the file gets written to system/tmp instead or if it's ok to access Contao's filesystem tools 'that early', ...

**Comment by ausi** [comment]
I think this might be a Contao issue. Using the filesystem tools should be OK in an `initializeSystem` hook IMO.

**Comment by ausi** [comment]
@m-vo As this got fixed in https://github.com/contao/contao/pull/1685 we can close the issue?

**Comment by m-vo** [comment]
Yes! :-)
