### ISSUE TITLE
Make config files editable again in Contao back end

### ISSUE THREAD

**Issue by kikmedia** [madeyourday/contao-rocksolid-custom-elements#116]
I just realized that in Contao versions from 4.7 upwards it is no longer possibe to edit the config files in back end due to https://github.com/contao/contao/commit/4c3a638ced3c9916669caf4768fd1950b4e28d86 (where now html5 and sql is hardcoded). In older versions, one could do this after enabling *.php as a valid template format.

I'm not shure how to solve this, I'm not even shure that this is a bug - BUT I personally think there should be a way to edit these *.php files in /templates.

**Comment by ausi** [comment]
Should be fixed in version 2.2.14

**Comment by kikmedia** [comment]
Works like a charm, thanks a lot!
