### ISSUE TITLE
HTML5 files are not shown in template folder / files can not be edited

### ISSUE THREAD

**Issue by zoglo** [madeyourday/contao-rocksolid-custom-elements#118]
Hello,

the new contao update (4.9.2) had some changes to template files:

[https://github.com/contao/contao/pull/1591](url)

When having RSCE installed, only .php files are shown and no file can be edited

**Comment by zoglo** [comment]
Removing the added file "tl_templates.php" from Issue#116 seems to fix this issue

**Comment by zoglo** [comment]
I created a pull request with a bugfix that I've successfully tested

**Comment by ausi** [comment]
Closed in favor of #119
