### ISSUE TITLE
Contao 4.9.2 : Modifizierte html5 Templates werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by chriza** [madeyourday/contao-rocksolid-custom-elements#120]
Hallo,

ich habe eine frische Contao 4.9.2 Installation. In dieser werden modifizierte html5 Templates im Backendbereich [Templates] angezeigt.

Nach Installation der Custom-Elements Erweiterung, werden diese nicht mehr angezeigt.

**Comment by pressi** [comment]
Duplicate? See #118 #119

**Comment by chriza** [comment]
duplicate
