### ISSUE TITLE
Select different templates

### ISSUE THREAD

**Issue by zonky2** [madeyourday/contao-rocksolid-custom-elements#122]
if I see it right, the config and the template file must have the same name - config file with sufix "_config"

It would be nice if you could select different template files and the binding to the names would not be so tight, i.e. to the config file 
`rsce_myfile_config.php`

`rsce_myfile_a.html5`
`rsce_myfile_b.html5`

**Comment by ausi** [comment]
> It would be nice if you could select different template files

This should already be possible, but the default template has to have the same name. The following example should work:

* *rsce_myfile_config.php*
* *rsce_myfile.html5* (default template)
* *rsce_myfile_a.html5*
* *rsce_myfile_b.html5*

**Comment by zonky2** [comment]
Hmm... I'll test it again...

**Comment by zonky2** [comment]
Okay - works well... probably had tomatoes on his eyes yesterday ;-)
