### ISSUE TITLE
File picker updates the wrong image when moving the element

### ISSUE THREAD

**Issue by zonky2** [madeyourday/contao-rocksolid-custom-elements#123]
I have a group of input elements that can be changed in order. An input element it a file picker.

If you move a group and do not save the content element but continue working and change an image, the image will be changed in another element group.

**Comment by ausi** [comment]
Which version of the custom elements extension do you use?

**Comment by zonky2** [comment]
Sorry...
Contao 4.9.4
RST-CE: 2.2.16
