### ISSUE TITLE
Globales Template wird nicht geladen. 

### ISSUE THREAD

**Issue by Tastaturberuf** [madeyourday/contao-rocksolid-custom-elements#124]
Contao 4.9.3
RSCE: 2.2.16

Ich habe das Template `templates/rsce_tao_icon_links.html5` erstellt. Im Modul wird es auch als global erkannt, er lädt allerdings das Original `templates/tao/rsce_tao_icon_links.html5` aus dem Theme-Ordner. 

![image](https://user-images.githubusercontent.com/1027521/86582409-df85dd80-bf81-11ea-9660-52b0f5274bb5.png)

**Comment by ausi** [comment]
Welches Theme wird auf der Seite verwendet auf der das Element ausgegeben wird?

**Comment by Tastaturberuf** [comment]
Das Tao mit den Demodaten.

**Comment by Tastaturberuf** [comment]
Eingebunden über das Seitenlayout.

**Comment by ausi** [comment]
Bei Verwendung einens Themes werden die Templates immer aus dem Order der mit dem Theme verknüpft ist geladen. Das ist das Standard-Verhalten von Contao. Dass `templates/tao/rsce_tao_icon_links.html5` geladen wird ist also korrekt.

**Comment by Tastaturberuf** [comment]
Wie kann ich das denn dann updatesicher überschreiben ohne in jedem Modul ein eigenes Templates einstellen zu müssen? Ich war der Meinung globale Templates werden immer als erstes geladen. 

global `templates/` -> theme `templates/tao` -> bundle `vendor/Resources/contao/templates` 😫

**Comment by ausi** [comment]
Die Reihenfolge ist: theme `templates/tao` -> global `templates/` ( -> bundle `vendor/Resources/contao/templates` ) 😫

Sie können also die Original-Templates direkt in den Template-Ordner verschieben und angepasste Template im Unterordner `templates/tao` pflegen.

**Comment by Tastaturberuf** [comment]
Danke, gut zu wissen. 👍
