### ISSUE TITLE
Custom elements are not assigned to user groups during Contao 4.9 migration

### ISSUE THREAD

**Issue by dmolineus** [madeyourday/contao-rocksolid-custom-elements#128]
When I update a Contao 4.4 project the `CeAccessMigration` of Contao assigns all existing elements/module to every user group. This works but not for rocksolid custom elements. They are ignored. It looks like that the config is not processed in the install tool/migration command.

https://github.com/madeyourday/contao-rocksolid-custom-elements/blob/a535e3e1edcecb32c88a3dbdcc3fb59875ad9570/src/CustomElements.php#L1072-L1087

I'm not sure if the issue occurs in the install tool and migration command, or only in one of this cases.

**Comment by ausi** [comment]
Does the issue get resolved if you remove the following lines? https://github.com/madeyourday/contao-rocksolid-custom-elements/blob/a535e3e1edcecb32c88a3dbdcc3fb59875ad9570/src/CustomElements.php#L1074-L1091

**Comment by ausi** [comment]
Should be fixed with 1493e60148ebbab7f4b7a5f26e75f66c8cec5db0
