### ISSUE TITLE
Example Code leads to exception

### ISSUE THREAD

**Issue by creffect** [madeyourday/contao-rocksolid-custom-elements#134]
The first example for a custom element (https://rocksolidthemes.com/de/contao/plugins/custom-content-elements/dokumentation)

```
<?php
// rsce_my_element_config.php
return array(
    'label' => array('Mein Element', 'Meine Beschreibung...'),
    'types' => array('content', 'module'),
    'contentCategory' => 'texts',
    'moduleCategory' => 'miscellaneous',
    'beTemplate' => 'be_rsce_my_element',
    'standardFields' => array('headline', 'cssID'),
    'wrapper' => array(
        'type' => 'none',
    ),
    'fields' => array(
        'text' => array(
            'label' => array('Text', 'Beschreibung...'),
            'eval' => array('rte' => 'tinyMCE'),
            'inputType' => 'textarea',
        ),
    ),
);
```

leads to the exception "Could not load template 'be_rsce_my_element'" after saving it in an article and reopening the article page in the contao backend. If you remove the line "beTemplate" it seems to work. Could you please check this?

**Comment by ausi** [comment]
The `beTemplate` setting is optional, you only need it if you want to use a different template for displaying the element in the backend.

The example code on the website was corrected now and should work without any error by default.
