### ISSUE TITLE
FR: possibilty to collapse items in list

### ISSUE THREAD

**Issue by neckarpixel** [madeyourday/contao-rocksolid-custom-elements#138]
Meanwhile I have an item list with 40 elements, there page in BE is really long. It would be nice, if you can collapse the items to shrink list.

**Comment by ausi** [comment]
Did you try using a `group` at the start of the elements fields?
https://rocksolidthemes.com/de/contao/plugins/custom-content-elements/dokumentation#feldtyp-group
