### ISSUE TITLE
Kategorie wird in der Backendvorschau nicht angezeigt

### ISSUE THREAD

**Issue by berecont** [madeyourday/contao-rocksolid-custom-elements#140]
[madeyourday/contao-rocksolid-custom-elements] 2.3.5 mit cto 4.12.0
Im Backend wird ohne eigenen Eintrag zur 'contentCategory' im CE immer 'Custom Elements (MeinSuperCE)' angezeigt - z.B. `Custom Elements (MeinSuperCE)`, bei Wrapper sollte `Wrapper (MeinSuperCE)` stehen
Wenn ich einen eigenen Eintrag zur 'contentCategory' mache, steht nur noch die Bezeichnung von 'label' - z.B. `(MeinSuperCE)`  
![2021-08-21 11_53_50-Artikel Start Inhaltselemente _ bulma412 local](https://user-images.githubusercontent.com/33038265/130322566-a8e8cad5-f70d-4819-8c37-519f94465a69.png)

**Comment by ausi** [comment]
Can you please try if this works now with `"madeyourday/contao-rocksolid-custom-elements": "dev-master",` ?

**Comment by berecont** [comment]
Yes, now it works

**Comment by ausi** [comment]
Great! Fixed in version 2.3.6 then.

**Comment by ausi** [comment]
So this issue can be closed again then?
