### ISSUE TITLE
Templateabfrage um Twig-Support erweitern

### ISSUE THREAD

**Issue by mj1985** [madeyourday/contao-rocksolid-custom-elements#147]
Moin,

wir nutzen Twig-Templates für Contao und haben dafür die folgende Zeile mit der Abfrage nach einem Twig-Template erweitert.

https://github.com/madeyourday/contao-rocksolid-custom-elements/blob/ab614faca64a871d097f3e140164cca9cce24ed4/src/CustomElements.php#L1376

Ändern in:
`if (file_exists(substr($configPath, 0, -11) . '.html5') || file_exists(substr($configPath, 0, -11) . '.html.twig')) {  `

Könnte vielleicht auch für andere interessant sein und es ist in die Erweiterung schaffen?

**Comment by vossmedien** [comment]
Danach hab ich auch gerade gesucht. Es wäre super, wenn man auch Twig Templates hernehmen könnte um beispielsweise auch Includes zu nutzen. Danke!

**Comment by ausi** [comment]
Twig sollte in Version 2.3.12 nun funktionieren.
