### ISSUE TITLE
preview or name in backend view?

### ISSUE THREAD

**Issue by JensB74** [madeyourday/contao-rocksolid-custom-elements#149]
Hi and thanks for the great plugin!

Is there a way to display a preview of the contents of the element, or a given name, in the backend?
If I have more than one of my own elements in an article, they all have the same name:
box
box
box
and I don't know what's inside until I click it ...

Or am I missing a setting in den _config.php that does exactly that?

Thanks in advance!

**Comment by ausi** [comment]
I the article view a preview of the content elements should be shown by default.
Can you post your *rsce_….html5* and *rsce_…_config.php* here?

**Comment by JensB74** [comment]
The contents were copied from the documentation and from this url:
https://github.com/fenepedia/contao-custom-elements

In backend it looks like this: https://ibb.co/RQW6XwB

This is my html5:
`<div class="<?php echo $this->class ?>" <?php echo $this->cssID ?>>
	<a href="<?php echo $this->url ?>">
		
		<?php if ($image = $this->arrData['getImageObject']($this->image)): ?>
			<figure class="image_container">
				<img src="<?php echo $image->src ?>" alt="<?php echo $image->alt ?>"<?php echo $image->imgSize ?>>
			</figure>
		<?php endif ?>
		<div class="info <?php echo $this->bgcol ?>">
			<span class="datum"><?php echo $this->datum ?></span> <br>
			<span class="ort"><?php echo $this->ort ?></span> <br>
			<strong><?php echo $this->teilnehmer ?></strong> <br>
			<?php echo $this->veranstaltung ?>
		</div>
	</a>
</div>`

and this the PHP:
`<?php
// rsce_my_element_config.php
return array(
    'label' => array('Programm-Box', 'Box-Element für die Startseit'),
    'types' => array('content', 'module'),
    'contentCategory' => 'texts',
    'moduleCategory' => 'miscellaneous',
    'beTemplate' => 'be_wildcard',
    'standardFields' => array('headline', 'cssID'),
    'wrapper' => array(
        'type' => 'none',
    ),

    'fields' => array(
	
		'bgcol' => array (
			'label' => array('Hintergrundfarbe', 'Wählen Sie hier die Hintergrundfarbe der Programm-Box'),
			'inputType' => 'select',
			'options' => array(
						'blau' => 'blau',
						'magenta' => 'magenta',
						'tuerkis' => 'türkis',
						'gelb' => 'gelb',
						'gruen' => 'grün',
					),
		),
		'image' => array(
			'label' => array('Bild', 'Ein Bild von dem/den Teilnehmer/n'),
			'inputType' => 'fileTree',
			'eval' => array(
				'fieldType' => 'radio',
				'filesOnly' => true,
				'extensions' => 'jpg,jpeg,png,gif,svg',
			),
		),
		'datum' => array(
            'label' => array('Datum', 'Das Datum und die Uhrzeit der Veranstaltung, z. B. Fr. 16.03.2022, 19.30 Uhr.'),
            'inputType' => 'text',
        ),
        'ort' => array(
            'label' => array('Ort', 'Der Ort der Veranstaltung.'),
            'inputType' => 'text',
        ),
        'teilnehmer' => array(
            'label' => array('Teilnehmer', 'Der oder die Teilnehmer der Veranstaltung.'),
            'inputType' => 'text',
        ),
        'veranstaltung' => array(
            'label' => array('Veranstaltung', 'Der Name der Veranstaltung. Neue Zeile per {{br}} einfügen.'),
            'inputType' => 'text',
        ),
		'url' => array(
			'label' => array('Link', 'Verlinkung mit der Detailseite hier einfügen.'),
			'inputType' => 'url',
		),
    
    ),
);`

**Comment by ausi** [comment]
If you remove the following line from your *rsce_programmbox_config.php*, the preview should be shown as expected:

```php
'beTemplate' => 'be_wildcard',
```

**Comment by JensB74** [comment]
Perfect, thanks a lot!!
