### ISSUE TITLE
dependOn - Werte der ausgeblendeten Felder werden nicht gespeichert.

### ISSUE THREAD

**Issue by medianetic** [madeyourday/contao-rocksolid-custom-elements#152]
Ich habe in einem CustomElement (Contao 4.9.33 und Custom Elements 2.3.12) mehrere abhängige Felder, bspw. wie folgt definiert:

```
'lang' => array(
            'label' => array(
                'de' => array('Sprache', '')
            ),
            'inputType' => 'select',
            'options'   => array('de','en','cz','ro'),
            'eval' => array(
                'mandatory' => true,
                'tl_class' => 'clr',
            ),
            'default'   => 'de',
        ),
        
        'name_de' => array(
            'label' => array('Name DE', ''),
            'eval' => array(
            ),
            'dependsOn' => array(
                'field' => 'lang',  
                'value' => 'de',      
            ),
            'inputType' => 'text',
            
        ),

        'name_en' => array(
            'label' => array('Name EN', ''),
            'eval' => array(
            ),
            'dependsOn' => array(
                'field' => 'lang',  
                'value' => 'en',      
            ),
            'inputType' => 'text',
            
        ),
```

Wenn man jetzt 'de' einstellt und dann 'name_de' speichert und dann anschließend 'en' selektiert und 'name_en' speichert ist 'name_de' wieder leer, d.h. er füllt das ausgeblendete Feld nicht mit dem Wert, den er vorher aber gespeichert hat (name_de). So sollte es doch nicht sein, dann würde die 'dependsOn' Eigenschaft gar keinen funktionellen Sinn ergeben?!

**Comment by ausi** [comment]
> So sollte es doch nicht sein

Doch. Die Einstellung `dependsOn` ist für Felder gedacht die nur dann Werte erhalten wenn die eingestellte Bedingung erfüllt ist.

Um Felder auszublenden dessen Werte aber gespeichert werden sollen, kann `dependsOn` nicht verwendet werden.

**Comment by medianetic** [comment]
Ok, verstehe. Das was ich vor habe ist dann mit dem CustomElement nicht abbildbar, oder?

**Comment by ausi** [comment]
Mit einer Gruppe pro Sprache könnte man eventuell ein ähnliches Ergebnis erreichen, je nach dem was genau gewünscht ist. <https://rocksolidthemes.com/de/contao/plugins/custom-content-elements/dokumentation#feldtyp-group>

**Comment by medianetic** [comment]
Ja danke guter Hinweis! Ich schließ das mal hier. Danke fürs schnelle Feedback.
