### ISSUE TITLE
'inputType' => 'picker' not working?

### ISSUE THREAD

**Issue by 463** [madeyourday/contao-rocksolid-custom-elements#159]
I tested the use of a picker. The configuration follows to [https://docs.contao.org/dev/reference/widgets/picker/]().

![grafik](https://user-images.githubusercontent.com/7769231/211803746-f7a3c7d0-9551-46f0-9a5a-7615a27bdf1c.png)

The backend throws an exception:

![grafik](https://user-images.githubusercontent.com/7769231/211804193-94b7b781-879b-4eff-b5b3-b2ddafc348d2.png)

Do I make a failure or pickers are actually not supported?

**Comment by 463** [comment]
![grafik](https://user-images.githubusercontent.com/7769231/211807782-f4041b10-0744-4c19-93e3-c94b4236f865.png)

**Comment by ausi** [comment]
You need to set `eval.context` because the relations are stored statically for each DCA and can therefore not be retrieved for “dynamic” fields: `'eval' => ['context' => 'dc.tl_news']`

Related ticket: #129

**Comment by 463** [comment]
Perfect. It is working.
Would be fine to add this as an example in [https://rocksolidthemes.com/de/contao/plugins/custom-content-elements/dokumentation]()

Thank you
