### ISSUE TITLE
Twig templates support

### ISSUE THREAD

**Issue by qzminski** [madeyourday/contao-rocksolid-custom-elements#165]
The `rsce_foobar.html.twig` templates seem to work fine, except when you try to extend the Contao base template:

```twig
{% extends “@Contao/content_element/_base.html.twig” %}
```

Then, you get the following error:

![CleanShot 2024-02-21 at 12 49 00@2x](https://github.com/madeyourday/contao-rocksolid-custom-elements/assets/193483/d630f880-d6a3-4ff5-9d09-e32e597d6b00)

It's obviously related to the fact that this file is treated as a legacy template, and thus has a different context. Possible solutions:

1. Copy-paste the required context from here: https://github.com/contao/contao/blob/796f20fb5e2d6db01f6d80b3820eff4c806b3be5/core-bundle/src/Controller/ContentElement/AbstractContentElementController.php#L85-L99
2. Convert this element to a service controller: https://github.com/madeyourday/contao-rocksolid-custom-elements/blob/master/src/Element/CustomElement.php

**Comment by ausi** [comment]
Regarding the switch to fragment controllers, see #162

**Comment by qzminski** [comment]
@ausi looks good at first sight, thanks!

**Comment by ausi** [comment]
Released as version 2.4.7
