### ISSUE TITLE
Incorrect output of  ID in Twig-Templates

### ISSUE THREAD

**Issue by mlwebworker** [madeyourday/contao-rocksolid-custom-elements#177]
Contao: 5.3.13
Rocksolid Custom Elements: 2.4.11 

Wenn ich in einem Twig-Template das Standardfeld cssID (z.B. `'standardFields' => array('headline', 'cssID')`)verwende und im Twig-Template folgenden Code schreibe:

```
<div class="{{ class }}" {{ cssID }}>
...
</div>
```

Dann wird  folgendes HTML generiert:

```
<div class="ce_rsce_elementname meine-Klasse" id=""meineID"">
...
</div>
```
Sind bei der ID also einmal Anführungszeichen zu viel.
Wenn ich die Variable` element_html_id` zur Ausgabe nutze, dann klappt es korrekt, aber dann müsste ich abfangen, das `id=` nur ausgegeben wird, wenn eine ID gesetzt wird und das finde ich etwas unschön.

**Comment by ausi** [comment]
Bei der Verwendung von `{{ cssID }}` wird die Ausgabe encoded wodurch dann `<div id=&quot;meineID&quot;>` rauskommt. Das wird in den dev-tools dann als `<div id=""meineID"">` angezeigt.

Man muss also entweder `{{ cssID|raw }}` verwenden, oder die neue Funktionsweise von den Twig-Templates nutzen:

```twig
<div{{ cssID|raw }}>

...oder...

<div{{ attrs().setIfExists('id', element_html_id) }}>

...oder...

<div id="{{ element_html_id }}">
```

Die neuen Twig-Variablen wie `element_html_id` werden seit Version 2.4.7 von der Erweiterung gesetzt. Siehe auch #165

**Comment by mlwebworker** [comment]
Danke für die Erklärung. Dann werde ich das entsprechend einsetzen.
