### ISSUE TITLE
BE-Template

### ISSUE THREAD

**Issue by MrTool** [madeyourday/contao-rocksolid-custom-elements#28]
Hi,

It would be great to define an special BE-Template or use an default one (only with field title etc.) and not to parse the whole element.

Parsing complex elements could lead into backend issues.

**Comment by MrTool** [comment]
Sure but i think this solution is a little bit "mäh"

Why not using the be wildcard template as default and a template in the same folder suffixed like the config file but with _be for special be templates?

**Comment by ausi** [comment]
I added the option `beTemplate`:

```php
<?php
return array(
	//...
	'beTemplate' => 'my_be_template',
	'fields' => array(
		//...
	),
);
```

**Comment by zonky2** [comment]
pls add `beTemplate` to the docs https://rocksolidthemes.com/de/contao/plugins/custom-content-elements/dokumentation

**Comment by ausi** [comment]
> pls add `beTemplate` to the docs

Done.
