### ISSUE TITLE
Fix date picker in list elements

### ISSUE THREAD

**Issue by ausi** [madeyourday/contao-rocksolid-custom-elements#31]
See <http://help.rocksolidthemes.com/discussions/contao/4789>.

Maybe we could use the solution from [assets/contao/js/core-uncompressed.js:421-439](https://github.com/contao/core/blob/0b3636ef2430e6ad3510dca8bdf839e962395161/assets/contao/js/core-uncompressed.js#L421-L439).

**Comment by christianromeni** [comment]
Yep.. The core does it on its own.. The function could be re-usable in your module..

**Comment by JT-007** [comment]
it looks like the same problem occurs with color pickers
