### ISSUE TITLE
Support other picker widgets

### ISSUE THREAD

**Issue by dmolineus** [madeyourday/contao-rocksolid-custom-elements#34]
If I use a 3rd party widget (f.e. https://github.com/netzmacht/contao-icon-wizard) within the custom elements extension which has a popup picker like the file or page tree widget, it's not working because the virtual field does not exists.

Affected conditions:
 - [CustomElements.php#L143-148](https://github.com/madeyourday/contao-rocksolid-custom-elements/blob/master/src/MadeYourDay/Contao/CustomElements.php#L143-148)
 - [CustomElements.php#L76-L93](https://github.com/madeyourday/contao-rocksolid-custom-elements/blob/master/src/MadeYourDay/Contao/CustomElements.php#L76-L93)

**Comment by ausi** [comment]
[CustomElements.php:76-93](https://github.com/madeyourday/contao-rocksolid-custom-elements/blob/3813cbd12ba7e086aa00f7bc7e7a6492d4eac225/src/MadeYourDay/Contao/CustomElements.php#L76-L93) gets never called from your extension because it doesn't execute `onload_callback`s.

Maybe your extension has to do something like [system/modules/core/controllers/BackendFile.php:70-72](https://github.com/contao/core/blob/1f7448f356cbef9299d7285b2b3068723e620eb1/system/modules/core/controllers/BackendFile.php#L70-L72)?

**Comment by ausi** [comment]
Next problem is that your extension tries to load the virtual field from the database [IconWizardController.php:59](https://github.com/netzmacht/contao-icon-wizard/blob/c14229e8510b4eba5e05f36bf893421d54fb0bb6/src/system/modules/iconWizard/controller/IconWizardController.php#L59) which fails `Unknown column 'rsce_field_icon' in 'field list'`

**Comment by ausi** [comment]
Another issue is that [CustomElements.php:49-51](https://github.com/madeyourday/contao-rocksolid-custom-elements/blob/3813cbd12ba7e086aa00f7bc7e7a6492d4eac225/src/MadeYourDay/Contao/CustomElements.php#L49-L51) will not pass. This check is necessary to check for requests like `contao/main.php?do=article&table=tl_content&id=1`.

**Comment by dmolineus** [comment]
Thanks for the hints. Had tried it some times ago and noticed that even if I create the DC_Table and trigger the callbacks it would fail because of the mentioned conditions. I'll prepare my extension to support this requirements.

**Comment by dmolineus** [comment]
I prepared the widget to support the onload_callback and load_callback. Still the above mentioned limitations in contao-rocksolid-custom-elements prevents them to work.

If you want to test it, it's currently only part of the develop branch.
https://github.com/netzmacht/contao-icon-wizard/tree/develop

**Comment by ausi** [comment]
It seems like your extension still tries to load the virtual field from the database. Please try the [draft/improve-compatibility](https://github.com/madeyourday/contao-rocksolid-custom-elements/tree/draft/improve-compatibility) branch and tell me if it works for your extension.

**Comment by dmolineus** [comment]
It works fine now with the changes in the branch. Thanks for the great and fast support.

**Comment by ausi** [comment]
It’s in the master branch now.
