### ISSUE TITLE
Custom elements not indexed?

### ISSUE THREAD

**Issue by rocchidavide** [madeyourday/contao-rocksolid-custom-elements#35]
It seems that text inside custom elements is not indexed by search engine.

Contao 3.4.4 - Custom Elements 1.2.9	 2

**Comment by ausi** [comment]
I wasn’t able to reproduce this issue. Does the text of your element appear in the source code of the page? You should also take a look at `<!-- indexer::stop -->` and `<!-- indexer::continue -->` comments in the page source code.

**Comment by rocchidavide** [comment]
Now it works... i don't know why, maybe because i purged the cache...  Thank you however, and thank you so much for this clever extension!

**Comment by ausi** [comment]
You’re welcome!
