### ISSUE TITLE
Add support for forms

### ISSUE THREAD

**Issue by ausi** [madeyourday/contao-rocksolid-custom-elements#37]
See http://help.rocksolidthemes.com/discussions/contao/7512

**Comment by jenda77** [comment]
Great, thank you very much. How can I add a custom element to a form now?

**Comment by ausi** [comment]
Add `form` to the `types` array in the element configuration file.

Before:

```php
'types' => array('content', 'module'),
```

After:

```php
'types' => array('content', 'module', 'form'),
```

**Comment by jenda77** [comment]
Great work! Thank you very much!
