### ISSUE TITLE
Manche Einträge lassen sich nicht mehr löschen

### ISSUE THREAD

**Issue by christianromeni** [madeyourday/contao-rocksolid-custom-elements#40]
Hallo,

ich habe festgestellt, das manche Custom Content Elements sich nicht mehr löschen lassen.
Diese haben dann ein grause statt ein rotes X:

![screen shot 2015-04-23 at 12 21 32](https://cloud.githubusercontent.com/assets/1358040/7295112/5271d31c-e9b3-11e4-844b-e094803e4507.png)

Ich habe aktuell keine Lösung dazu gefunden... Gibt es ein bekanntes Problem dazu?

**Comment by ausi** [comment]
Handelt es sich um einen Administrator-Account?

Mit welchen Schritten kann der Fehler reproduziert werden?

Welche Erweiterungs-Version? Welche Contao-Version? Wie sieht die Konfiguration des Elements aus?

**Comment by christianromeni** [comment]
Ja
Ich weiß es leider nicht, habe nur vorhin festgestellt das es so ist.
v1.2.9
v3.4.5

```php
return array(
    'label' => array('Kontakt Box | Sidebar', ''),
    'types' => array('content'),
    'contentCategory' => 'Custom Content Elements',
    'standardFields' => array('cssID'),
    'wrapper' => array(
        'type' => 'none',
    ),
    'fields' => array(
      'headline_text' => array(
        'label' => array(
          'Überschrift [DE]', ''
        ),
        'eval' => array('maxlength' => 255,'tl_class'=>'w50','allowHtml'=>true),
        'inputType' => 'text',
      ),
      'headline_text_en' => array(
        'label' => array(
          'Überschrift [EN]', ''
        ),
        'eval' => array('maxlength' => 255,'tl_class'=>'w50','allowHtml'=>true),
        'inputType' => 'text',
      ),
      'headline' => array(
        'label' => array(
          'Ansprechpartner', 'Bitte Ansprechpartner eintragen'
        ),
        'eval' => array('maxlength' => 255,'tl_class'=>'w50'),
        'inputType' => 'standardField',
      ),
      'email' => array(
        'label' => array(
          'E-Mail Adresse', ''
        ),
        'eval' => array('maxlength' => 255,'tl_class'=>'w50'),
        'inputType' => 'text',
      ),
      'phone' => array(
        'label' => array(
          'Telefon Nummer', ''
        ),
        'eval' => array('maxlength' => 255,'tl_class'=>'w50'),
        'inputType' => 'text',
      ),
	'images' => array(
		'label' => array('Kontaktbild auswählen', ''),
		'eval' => array('fieldType'=>'radio', 'filesOnly'=>true, 'tl_class'=>'w50 clr'),
		'inputType' => 'fileTree',
	),
    ),
);
```

**Comment by ausi** [comment]
Haben Sie eventuell ein Inhaltselement vom Typ „Include-Elemente › Inhaltselement“ angelegt, das auf dieses Inhaltselement verweist?

**Comment by christianromeni** [comment]
öhm... Jap......... :-)
Ich wusste nicht das überprüft wird ob die irgendwo in verwendung sind.....
Alles klar... :)

**Comment by ausi** [comment]
Weitere Fragen dieser Art bitte über das [Contao-Community-Forum](https://community.contao.org/de/) stellen oder ein Ticket über <https://my.rocksolidthemes.com/support> anlegen.
