### ISSUE TITLE
More templates for one .php file?

### ISSUE THREAD

**Issue by rocchidavide** [madeyourday/contao-rocksolid-custom-elements#41]
Is it possible to select the .html5 template to load inside a _config.php file? The idea is to have more templates for one config file

**Comment by ausi** [comment]
There is no such option built in, but you can `include` other templates in the template itself. e.g.:

A field in the config:

```php
'myTemplate' => array(
	'label' => array('Template', ''),
	'inputType' => 'select',
	'options' => array(
		'my_template_1',
		'my_template_2',
		'my_template_3',
	),
),
```

Template:

```php
<?php include __DIR__ . '/' . $this->myTemplate . '.html5';
```
