### ISSUE TITLE
Image Crop

### ISSUE THREAD

**Issue by Messa1** [madeyourday/contao-rocksolid-custom-elements#42]
Ist es möglich die Skallierungsmethode zu wählen?
Im Beispiel von euch für die Mitarbeiterliste konnte ich das entnehmen.
Dadurch wird das Bild zwar neu erstellt und Center Center skaliert. 
```
<?php if ($image = $this->arrData['getImageObject']($slides->image, array(1000, 800))): ?>
```
Wie kann ich die Skallierungsmethode noch abändern?

**Comment by fritzmg** [comment]
Mit dem dritten Wert des size arrays. Also zB
```php
<?php if ($image = $this->arrData['getImageObject']($slides->image, array(1000, 800, 'proportional'))): ?>

**Comment by ausi** [comment]
Für Fragen zu Contao bitte an <https://community.contao.org/> wenden. Der Issue-Tracker auf GitHub ist für Fehlerberichte gedacht.

**Comment by xApep** [comment]
@ausi or @fritzmg 
This does not work in Contao 4.11.5.

If you set size bigger then actual side of a source image it does not do anything, but if it is smaller then that then it resize it.

**Comment by ausi** [comment]
@xApep https://community.contao.org/

**Comment by fritzmg** [comment]
@xApep that's normal, although if you use a pre-defined image size (either via the database or your config) Contao will "copy" the source image to `assets/images/` (without resizing it) in this case, unless `skip_if_dimensions_match` is set to `false`.

* https://docs.contao.org/dev/reference/config/#contao-bundle-configuration
* https://docs.contao.org/dev/framework/image-processing/image-sizes/

**Comment by xApep** [comment]
@fritzmg I know this was not "normal" in contao 3, that is why i thought that something is buggy. Probably there is no way to force smaller images to crop to bigger sizes right?

**Comment by fritzmg** [comment]
> @fritzmg I know this was not "normal" in contao 3, that is why i thought that something is buggy.

Yes, this changed in Contao 4. Contao 4 no longe upscales images, as this is unnecessary. If you want to upscale your images, you need to do it via CSS.

**Comment by xApep** [comment]
@fritzmg thank you for all the info.
