### ISSUE TITLE
Content element class "" (content element "rsce_foo") does not exist

### ISSUE THREAD

**Issue by fritzmg** [madeyourday/contao-rocksolid-custom-elements#43]
I have a strange problem in one Contao installation:

If a specific backend user is logged into the backend and he opens the frontend, he is unable to see any of the rocksolid custom elements and the system log is filled with these messages
```
Content element class "" (content element "rsce_widget_social") does not exist
```
One for each custom element that would otherwise be displayed in the frontend.

So far it only happens if a specific backend user is logged into the backend. It does not happen if you are not logged into the backend and it does not happen with other users when they visit the frontend while being logged into the backend.

**Comment by ausi** [comment]
Please check if the file *system/cache/rocksolid_custom_elements_config.php* exists and includes a definition for the element `rsce_widget_social`. Also check if the error still occurs if all other extensions are disabled.

**Comment by fritzmg** [comment]
Yes, the file `system/cache/rocksolid_custom_elements_config.php` definitely exists and it does have a definition for all the custom elements used on the page (otherwise it wouldn't work for anyone else I guess)?

Testing whether this occurs in Contao's safe mode takes a bit more time, since the custom elements are currently included into the page layout via extensions (e.g. boxes4ward).

**Comment by fritzmg** [comment]
Ok, I think I have narrowed it down. I deacativated all extensions (except the rocksolid ones) in the system settings and then activated all of them one by one again, each time reloading the frontend with the affected user. As soon as I enabled the [netzmacht/contao-font-awesome](https://github.com/netzmacht/contao-font-awesome) extension, the problem occurred. The widgets were not visible in the frontend for this one user and the backend is filled with the aforementioned error messages.

This is a screenshot of the minium of activated modules that cause the problem:

![screenshot](https://cloud.githubusercontent.com/assets/4970961/8032734/b6d83e9c-0dd8-11e5-9434-92d69c28e889.png)

`!composer` and `metapalettes` need to be active for `netzmacht/contao-font-awesome` to work.

**Comment by fritzmg** [comment]
It seems the problem is not related to a specific user, but actually to a specific client computer or browser. If we log ourselves in on this machine (it's a MacBook Pro), no matter which user, the problem occurs. It also does not matter which browser we use (tested with FireFox, Safari and Chrome).

It's pretty weird o_0

**Comment by ausi** [comment]
It looks like a problem with the `initializeSystem` hook. Does it help if you comment the line [system/modules/font-awesome/config/config.php:36](https://github.com/netzmacht/contao-font-awesome/blob/4fff9f5c0b587126c51cc33dbeeda9aa8fc98db6/module/config/config.php#L36) out?

**Comment by fritzmg** [comment]
Yes, if I deactivate the `initializeSystem` hook of the font-awesome extension everything works on the affected machine. I debugged a little bit further and it's still strange: if I leave the hook active __but__ instead remove the content of the `Netzmacht\FontAwesome\FontAwesome::initialize()` function, i.e.
```php
	public function initialize()
	{/*
		if(!$this->isActive()) {
			return;
		}

		$this->loadDynamicTemplates();
		$this->initializeAssets();*/
	}
```
the rocksolid custom elements still do not work on the affected machine, even though the hook technically isn't doing anything at all. This means the construction of the `Netzmacht\FontAwesome\FontAwesome` object is actually the cause of the problem. So far I have narrowed it down to this function call in the `__construct` method of the class:
```php
$this->detectDebugMode();
```
I am currently debugging further.

**Comment by fritzmg** [comment]
I have narrowed it down to this call so far:
```php
$user = \UserModel::findByPk($userId);
```
within [Bit3/Contao/ThemePlus/ThemePlusEnvironment::getInstance()](https://github.com/netzmacht/contao-theme-plus/blob/support/4.x/src/Bit3/Contao/ThemePlus/ThemePlusEnvironment.php#L76).

Call stack:

* [Netzmacht/FontAwesome/FontAwesome::__construct()](https://github.com/netzmacht/contao-font-awesome/blob/master/src/Netzmacht/FontAwesome/FontAwesome.php#L44)
* [Netzmacht/FontAwesome/FontAwesome::detectDebugMode()](https://github.com/netzmacht/contao-font-awesome/blob/master/src/Netzmacht/FontAwesome/FontAwesome.php#L183)
* [Bit3/Contao/ThemePlus/ThemePlusEnvironment.php::isDesignerMode()](https://github.com/netzmacht/contao-theme-plus/blob/support/4.x/src/Bit3/Contao/ThemePlus/ThemePlusEnvironment.php#L173)
* [Bit3/Contao/ThemePlus/ThemePlusEnvironment::getInstance()](https://github.com/netzmacht/contao-theme-plus/blob/support/4.x/src/Bit3/Contao/ThemePlus/ThemePlusEnvironment.php#L46)
* when `$user = \UserModel::findByPk($userId);` is executed there, the rocksolid custom elements do not work anymore

**Comment by fritzmg** [comment]
Well, it's fixed - problem was caused by my own stupidity ;). I emptied the array of my custom content elements with
```php
$GLOBALS['TL_CTE']['widgets'] = array();
```
(`widgets` is the group name where I put my custom elements) in my `initconfig.php` (for reasons I don't remember...).

This was not a problem on some clients due to different executing orders of various hooks.
