### ISSUE TITLE
TL_FILES_URL wird nicht richtig aufgelöst

### ISSUE THREAD

**Issue by wschwaiger** [madeyourday/contao-rocksolid-custom-elements#44]
Das Problem tritt in der Front-End Ansicht auf. Bsp siehe hier http://pha.at/verkaufspferde.html - Eine Bereinigung des Contao-Caches bringt kurze Abhilfe, danach wird aber wieder nicht geladen.

Contao Version 3.4.5
Custom Elements 1.2.9

![bildschirmfoto 2015-06-11 um 10 55 17](https://cloud.githubusercontent.com/assets/458603/8103391/5e8c35ac-1028-11e5-8cfb-6fb288d56203.png)

Danke für schnelle Abhilfe,
Wolfgang Schwaiger

**Comment by wschwaiger** [comment]
Ist das immer noch nicht behoben in Contao selbst?

**Comment by ausi** [comment]
Für Fragen zu Contao bitte an <https://community.contao.org/> wenden. Der Issue-Tracker auf GitHub ist für Fehlerberichte gedacht die die Erweiterung betreffen.
