### ISSUE TITLE
IF Abfrage im STOP-Element eines Wrappers

### ISSUE THREAD

**Issue by Nico0o** [madeyourday/contao-rocksolid-custom-elements#50]
Es ist nicht möglich eine IF Abfrage im STOP-Element eines Wrappers auf das START Element zu machen. Hat z.B. den Nachteil das man einen DIV-Container nicht mit einer Abhängigkeit schließen kann.

**Comment by ausi** [comment]
Die Wrapper-Elemente der Custom Elements verhalten sich genau so wie alle Wrapper-Elemente in Contao. Für Fragen zu Contao bitte an <https://community.contao.org/> wenden. Der Issue-Tracker auf GitHub ist für Fehlerberichte gedacht die die Erweiterung betreffen.
