### ISSUE TITLE
List items collapsable

### ISSUE THREAD

**Issue by rocchidavide** [madeyourday/contao-rocksolid-custom-elements#55]
How about make list items collapsable? When I have many of those each of which has many fields, it's difficult to scroll and read them.

Thank you!

**Comment by ausi** [comment]
You can already do that by adding a group field as the first field in a list. E.g.:

```php
'my_group' => array(
	'inputType' => 'group',
	'label' => array('My Group', ''),
),
```

**Comment by rocchidavide** [comment]
What I mean is that:

```php
'members' => array(
            'label' => array('Feature boxes', ''),
            'inputType' => 'list',
            'elementLabel' => 'Feature box %s',
            'fields' => array(...)
```

**Comment by ausi** [comment]
I mean:

```php
'members' => array(
    'label' => array('Feature boxes', ''),
    'inputType' => 'list',
    'elementLabel' => 'Feature box %s',
    'fields' => array(
        'my_group' => array(
            'inputType' => 'group',
            'label' => array('My Group', ''),
        ),
        ...
    ),
),
```

**Comment by rocchidavide** [comment]
Sorry ausi, I'm also using group inside my member field. What i suggest i something like that:

![schermata 2015-08-11 alle 14 26 52](https://cloud.githubusercontent.com/assets/4699633/9197518/25862c12-4035-11e5-811f-ba63eab2a691.png)

**Comment by ausi** [comment]
With groups it would look like this:

![groups-collapsed](https://cloud.githubusercontent.com/assets/367169/9197637/282cc1aa-4036-11e5-9891-f579c133bf0a.png)

**Comment by rocchidavide** [comment]
I have more than one group inside my member field, but they are all uncollapsed

**Comment by ausi** [comment]
But you can collapse them by clicking on the group label.
Adding another level that is collapsible seems too much to me.

**Comment by rocchidavide** [comment]
Ok :) Thank you!

**Comment by xantippe** [comment]
similar question at forum
http://help.rocksolidthemes.com/discussions/contao/12021-verbesserungsvorschlag-fr-inputtype-list-icon-zum-zuklappen-der-items-im-be
