### ISSUE TITLE
I dont see the backend Module "My Custom Elements" after installing custom-elements

### ISSUE THREAD

**Issue by mafudelaptu** [madeyourday/contao-rocksolid-custom-elements#58]
below "Content" in Backend-navigation i dont get a new Module "My Custom Elements" (
or similar). 

contao version: 3.5.0

**Comment by ausi** [comment]
This Contao extension doesn’t add a backend module to the backend navigation. You have to create *rsce_XXX.html5* and *rsce_XXX_config.php* files in your template folder to create a new custom element. You can find the documentation of the extension here: <http://rocksolidthemes.com/de/contao/plugins/custom-content-elements/dokumentation>
