### ISSUE TITLE
Not working with PHP7

### ISSUE THREAD

**Issue by TB1234** [madeyourday/contao-rocksolid-custom-elements#59]
The rocksolid-custom-elements is not compatible with PHP 7. The reason is, that this extension us the \String class of Contao. This one was replaced with \StringUtil in 3.5.5 because in PHP 7 it is not allowed to use classes like String any more.

**Comment by ausi** [comment]
Please try the latest version from the master branch.

**Comment by TB1234** [comment]
Yes, Plugin is working but extension list not.
-> Function ("getExtensionList") is not a valid method for this service

I only use the RockSolid Extensions for different Templates (Swissy, 80/20, Open Sauce)

**Comment by ausi** [comment]
The extension list is part of the Contao core. If the error is not related to the Custom Elements extension, we can not fix it here.

**Comment by TB1234** [comment]
It's a long time ago I started this thread but if someone get the following message I have the solution

> Function ("getExtensionList") is not a valid method for this service

Remove the wsdl cache file which is stored in the /tmp folder. After that it works...
