### ISSUE TITLE
Error since 3.5.6 with elements

### ISSUE THREAD

**Issue by m-knorr** [madeyourday/contao-rocksolid-custom-elements#60]
We recognized a problem with some of our ce-elements created with rsce!

The save process doesn't works due to a javascript error.

```javascript
An invalid form control with name='rsce_field_items__rsce_dummy__headline' is not focusable.
```

hope the error is traceable!

**Comment by ausi** [comment]
Did you use the latest version (1.3.7) of the extension?

**Comment by m-knorr** [comment]
Yes. We use the current version of composer-client, custom-elements and contao. :(

**Comment by ausi** [comment]
Please clear the browser cache and check if that fixes the error. If the error still appears, please send us the *rsce_…_config.php* file.

**Comment by ausi** [comment]
Did clearing the browser cache fix the issue?

**Comment by NicolasSchneider** [comment]
I'm having the same issue with `madeyourday/contao-rocksolid-custom-elements@v1.3.9` and `contao/core@3.5.6`.

Clearing the browser cache did not resolve the problem.

**Comment by ausi** [comment]
Are you using a modified *tinyMCE.php* file? If so, please perform the changes of Contao 3.5.6: https://github.com/contao/core/commit/c16e537f33d51767b773416094a8c3f0bd9b704f

See contao/core#8131

**Comment by NicolasSchneider** [comment]
I'll try that later today, thanks. Seems like that would fix it.

**Comment by ausi** [comment]
@m-knorr, @NicolasSchneider does this issue still appear?

**Comment by nico-schneider** [comment]
@ausi It doesn't any more on clean installations for me.

**Comment by m-knorr** [comment]
thanks!
