### ISSUE TITLE
Input Type Group with state

### ISSUE THREAD

**Issue by christianromeni** [madeyourday/contao-rocksolid-custom-elements#63]
I was trying to add a group to my backend that is collapsed by default...
Would be a nice feature.

Something like:

```
          'description' => array(
            'label' => array('MyGroup', 'This is my collapsed group'),
            'inputType' => 'group',
            'collapsed' => true,
          ),
```

**Comment by jenda77** [comment]
:+1:

**Comment by ausi** [comment]
This is now implemented for groups and lists:

```php
'eval' => array('collapsed' => true),
```

**Comment by fkaminski** [comment]
Das greift bei mir nicht mit Contao 4.4..18 ?

**Comment by ausi** [comment]
The collapsed state of groups is stored in the session.  
Did you purge the session data in your user profile?

**Comment by ausi** [comment]
Did you purge “User profile › Clear cache › Purge data › Session data” too?

**Comment by fkaminski** [comment]
Nope - Sorry, this helps ...
