### ISSUE TITLE
Contao 4.1 - TemplateInheritance error

### ISSUE THREAD

**Issue by kalterwind** [madeyourday/contao-rocksolid-custom-elements#64]
In der Systemwartung (wenn ich das erstellte Element aus der Vorlage - rsce_boxes -  auswähle erhalte ich ebenso Fehler):

`Warning: include(/www/htdocs/XXXXX/vendor/madeyourday/contao-rocksolid-custom-elements/templates/be_rsce_convert.html5): failed to open stream: No such file or directory in /www/htdocs/XXXXX/vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php on line 88

Warning: include(): Failed opening '/www/htdocs/XXXXX/vendor/madeyourday/contao-rocksolid-custom-elements/templates/be_rsce_convert.html5' for inclusion (include_path='.:/usr/share/php:..') in /www/htdocs/XXXXX/vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php on line 88`

_Installiert unter system/modules/rocksolid-custom-elements/_

Gruss aus Bremen

**Comment by ausi** [comment]
Existiert die Datei */vendor/madeyourday/contao-rocksolid-custom-elements/templates/be_rsce_convert.html5* bzw. der Ordner */vendor/madeyourday/contao-rocksolid-custom-elements/* auf dem Webspace?

**Comment by kalterwind** [comment]
Nein.

**Comment by ausi** [comment]
Wurde die Erweiterung korrekt installiert, wie hier beschrieben unter dem Punkt „Erweiterungen installieren“? http://rocksolidthemes.com/de/contao/blog/contao-4-composer-theme-installieren

**Comment by kalterwind** [comment]
Nein, kann ich auch nicht. Contao 4.1 habe ich auf anderem Wege installiert.. mit dem normalen installer der mittlerweile dabei ist.

Neue Erweiterungen trage ich in die AppKernel.php ein mit:
`new ContaoModuleBundle('rocksolid-custom-elements',$this->getRootDir()),`

Das funktioniert bis jetzt auch bei allen eigenen und externen Erweiterungen. Nur hier nicht.

Ich habe mir die Seite jetzt noch mal angesehen und über SSH
`curl -sS https://getcomposer.org/installer | php`
ausgeführt und die Einträge in die AppKernel und composer.json angepasst.

Führe ich `php composer.phar update madeyourday/*` aus, erhalte ich `PHP Fatal error:  Class 'Contao\Composer\ComponentInstaller' not found in phar:///....`

**Comment by ausi** [comment]
Die manuelle Installation der Erweiterung wird derzeit nicht unterstützt.

Eventuell hilft es wenn Sie zuvor `php composer.phar install --no-plugins` und danach `php composer.phar update madeyourday/*` ausführen.

**Comment by kalterwind** [comment]
Nach dem ersten Teil erhalte ich:

`Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
**Your requirements could not be resolved to an installable set of packages.**
  Problem 1
    - league/uri 4.0.1 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
    - league/uri 4.0.1 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
    - Installation request for league/uri 4.0.1 -> satisfiable by league/uri[4.0.1].`

Contao läuft zwar per CGI auf PHP 5.6 aber der grundsätzliche Server auf dem viele andere Dinge von uns sind läuft mit 5.4, ich habe von der Kommandozeile nicht so viel Ahnung, wie ich das änder... .

Dann schreibe ich für meinen Fall wohl ehr eine eigene Erweiterung, das geht wohl schneller. Vielleicht geht es ja bald mit manueller Installation.

**Comment by ausi** [comment]
Mit dem Command `which php` kann herausgefunden werden welches Executable für den `php` command verwendet wird. Angenommen `which` gibt den Pfad `/usr/bin/php54/php` aus, dann kann vermutlich `/usr/bin/php56/php composer.phar` korrekt aufgerufen werden.

**Comment by kalterwind** [comment]
`php56 composer.phar install --no-plugins`
funktionierte. Lief alles soweit durch.

Sehe nun auch keine Fehler mehr.
Ich danke für deine Hilfe, ich habe jetzt zwar eine eigene Erweiterung für mein vorhaben geschrieben, aber für die Zukunft ist eure Lösung manchmal einfacher und schneller :)
