### ISSUE TITLE
Width and Height constraint in custom element

### ISSUE THREAD

**Issue by MartianGreed** [madeyourday/contao-rocksolid-custom-elements#67]
Hello,

i've been working for days with your extension and it's such a pleasure to work with it!!
I am currently in need to add a constraint for height and width, i don't know if it's possible now to do this at the moment?!

Have you got an idea?

**Comment by ausi** [comment]
You can define maximum and minimum values in the evaluation array, e.g.:

```php
'eval' => array(
	'minval' => 10,
	'maxval' => 100,
),
```

More information about Contao DCAs can be found in the Contao documentation: <https://docs.contao.org/books/api/dca/reference.html#evaluation>.
