### ISSUE TITLE
related tables

### ISSUE THREAD

**Issue by rocchidavide** [madeyourday/contao-rocksolid-custom-elements#69]
Is it possible to set a field to select a content of type 'alias' ? I would like to select a content element in my rsce custom element

**Comment by ausi** [comment]
You can use almost all features of Contao DCAs inside the custom elements config. Selecting a Content-Element could look like this:

```php
'elementId' => array(
	'label' => array('Content Element', ''),
	'inputType' => 'select',
	'options_callback' => array('tl_content', 'getAlias'),
	'eval' => array('chosen' => true),
),
```
