### ISSUE TITLE
Not working with Contao 4.2?

### ISSUE THREAD

**Issue by christianromeni** [madeyourday/contao-rocksolid-custom-elements#70]
I could not get the custom elements to work with contao 4.2.

I tried around a bit, and I think I could narrow it down to this line in the composer.json:

"symfony/symfony": "~2.8|~3.0",

I guess when using symphony 3.0, its not working. because when I delete 3.0, I can see elements in the frontend. but I get an error in the cache management:

```
[Symfony\Component\Debug\Exception\ClassNotFoundException]
  Attempted to load class "Psr6CacheClearer" from namespace "Symfony\Component\HttpKernel\CacheClearer".
  Did you forget a "use" statement for another namespace?
```

So I guess that 3.0 is needed by some new cacheing function that was implemented with 4.2

When running symphony 3.0, I get the following message in the profiler:
![image](https://cloud.githubusercontent.com/assets/1358040/16285322/bf4af0fa-38d5-11e6-90cf-8f34407041c2.png)

I'm not sure how I could fix that.. Since there is no more error then that...

**Comment by ausi** [comment]
This should be fixed now, please update the extension to the latest version 1.3.11.

**Comment by christianromeni** [comment]
Yep.. That seems to fix it! Thx for the fast fix! ;)

**Comment by christianromeni** [comment]
I would just re-open this, since I think its related..
Could it be that custom content elements are not working with symfony/symfony v3.1.2?

**Comment by ausi** [comment]
They should run fine with Symfony 3.1.2 and Contao 4.2.0.

What do you mean by “not working”?

**Comment by christianromeni** [comment]
There is no error at all, nothing.. just not working...
And I have another installation where all works well...
I'm not sure how we could find a good way to debug it..

**Comment by ausi** [comment]
It could eventually be related to symlinks, please take a look at the this ticket: http://help.rocksolidthemes.com/discussions/contao/15723

**Comment by christianromeni** [comment]
It actually is exactly that problem :-)
Thx
