### ISSUE TITLE
Symlinks in Repo

### ISSUE THREAD

**Issue by bcat-eu** [madeyourday/contao-rocksolid-custom-elements#73]
Typical use case on a DigitalOcean Droplet with stock LAMP and `composer require` would not show any errors but wouldn't create symlinks (https://github.com/madeyourday/contao-rocksolid-custom-elements/tree/master/src/MadeYourDay/Contao/Resources/contao - they'll be plain files). So I follow install process and get no feedback but also nothing works.

The `--prefer-source` solution would only work if git is installed and available in path as `git`.

Considering all above I'd think about automating the source / destination relations using some local tool and keeping normal (duplicate) directories in repo.

**Comment by ausi** [comment]
Duplicate directories in the repo is not a great solution, because it makes future changes much harder. I think we should split the extension into a new version *2.0* that drops support for Contao 3 and keep the *1.x* version with bugfixes for Contao 3.

**Comment by ausi** [comment]
This was fixed in version 2.0.0
