### ISSUE TITLE
Fix backend styles for Contao 4.3

### ISSUE THREAD

**Issue by ausi** [madeyourday/contao-rocksolid-custom-elements#75]

**Comment by m-vo** [comment]
There are as well some problems with smaller viewports and the flexible BE theme.

![style_err2](https://user-images.githubusercontent.com/5305677/27536851-443a327c-5a71-11e7-96a0-d66e32bf5195.png)

![style_err1](https://user-images.githubusercontent.com/5305677/27536850-4437c7b2-5a71-11e7-9333-f66a15755e40.png)

**Comment by websolutions-hamburg** [comment]
There is also a small issue for the description on the **Maintenance** page. The left margin is missing.

<img width="1073" alt="bildschirmfoto" src="https://user-images.githubusercontent.com/26099903/28195859-2fba555e-684d-11e7-9401-2b24985ed84e.png">

**Comment by websolutions-hamburg** [comment]
A little css fix. I think the class `p.rsce_group_description` need this margin to have the same distances like the other elements:

```css
p.rsce_group_description {
    margin: 10px 15px 20px;
}
```

**Comment by ausi** [comment]
Fixed in bea5668db57479c049c01f1c980fc37d6dfe2689. Thank you @m-vo and @websolutions-hamburg
