### ISSUE TITLE
Can't show fields in user with limited permissions

### ISSUE THREAD

**Issue by rocchidavide** [madeyourday/contao-rocksolid-custom-elements#76]
I made a custom element 'Titolo pagina', I set up a user group X with limited permissions, I checked that this element must be visible to the user group:

![image](https://cloud.githubusercontent.com/assets/4699633/23824549/fa154e12-0678-11e7-9f45-7b090d184fbc.png)

The problem is that when I log in with a user member of the user group X, I can enter in edit of my custom element but I can't see fields:

![image](https://cloud.githubusercontent.com/assets/4699633/23824533/b2f300c4-0678-11e7-8c36-e737a451bafb.png)

Contao version: 3.5.16
Rock Solid Custom Elements version: 1.3.10	11

**Comment by ausi** [comment]
Did you activate „tl_content › Custom Elements Data“ in the „Allowed fields“ section?
