### ISSUE TITLE
DCA-Picker does not work when Updating to Contao 4.4.1

### ISSUE THREAD

**Issue by Xendiadyon** [madeyourday/contao-rocksolid-custom-elements#79]
In Contao 4.4.0, there was a bug where the DCA-Picker could not be opened with reduced rights.
They fixed it, but now the DCA-Picker does not work anymore for Rocksolid Custom Elements.
https://github.com/contao/core-bundle/issues/959

**Comment by Xendiadyon** [comment]
The DCA-Picker will be rewritten for 4.4.2 and/or 4.5.0. However, do you have a quick workaround (other than granting admin rights for everyone?)

**Comment by ausi** [comment]
Should be fixed with the latest version (2.0.3) of the extension.

**Comment by Xendiadyon** [comment]
You are a genius. Thank you!
