### ISSUE TITLE
Adding images: use or override Metadata

### ISSUE THREAD

**Issue by Xendiadyon** [madeyourday/contao-rocksolid-custom-elements#81]
Good morning :)

We are using a Teaser-Box, where we can implement teaser images:
![image](https://user-images.githubusercontent.com/2657385/28204822-b8c6bcde-687f-11e7-9915-54d00964e992.png)

However, in Contao 4.4(.1), there is a new field "override Metadata" when adding images.
In the actual configuration it is not possible to add or edit the Metadata.

Is there an easy way to implement the "override Metadata" field or automatically import the metadata from the file-manager?

I can get the Metadata out of the FilesModel
![image](https://user-images.githubusercontent.com/2657385/28205257-8b46ef02-6881-11e7-99b8-b5027f993128.png)
But I have to check how I could pass the meta-Data to the  `\Picture::create()` routine.

**Comment by Xendiadyon** [comment]
Okay, Adding the copyright was rather easy, as I can set it outside of the $this->insert('picture_default', ...) routine.

![image](https://user-images.githubusercontent.com/2657385/28205694-622f5512-6883-11e7-90e0-9ce10de75968.png)

But I still can't add an alt-Attribute, less a self-defined alt-Attribute

**Comment by ausi** [comment]
If you use `$this->getImageObject()`, the alt text from the file manager should get applied automatically.
