### ISSUE TITLE
Add <h2> to rsce_list_item_title in BE

### ISSUE THREAD

**Issue by NinaG** [madeyourday/contao-rocksolid-custom-elements#83]
At the moment you show list items in backend like this:
`<div class="rsce_list_item_title" data-rsce-label="Box %s">Box 1</div>`

Please change it to this:
`<div class="rsce_list_item_title" data-rsce-label="Box %s"><h2>Box 1</h2></div>`

This would be a huge help for screen reader users. Thank you very much.

**Comment by ausi** [comment]
Fixed. Thank you for reporting this issue.
