### ISSUE TITLE
Please add alt-Attributes to toolbar-icons

### ISSUE THREAD

**Issue by NinaG** [madeyourday/contao-rocksolid-custom-elements#84]
At the moment alt-attributes are empty in toolbar-icons:
`<div class="rsce_list_toolbar"><a href="" class="rsce_list_toolbar_up" onclick="rsceMoveElement(this, -1);return false;" title="" data-rsce-title="Eine Position nach oben verschieben"><img src="system/themes/flexible/icons/up.svg" alt="" width="13" height="16"></a> <a href="" class="rsce_list_toolbar_down" onclick="rsceMoveElement(this, 1);return false;" title="" data-rsce-title="Eine Position nach unten verschieben"><img src="system/themes/flexible/icons/down.svg" alt="" width="13" height="16"></a> <img src="system/themes/flexible/icons/drag.svg" alt="" class="drag-handle rsce_list_toolbar_drag" title="" width="16" height="16"> <a href="" class="rsce_list_toolbar_delete" onclick="rsceDeleteElement(this);return false;" title="" data-rsce-title="Element löschen"><img src="system/themes/flexible/icons/delete.svg" alt="" width="16" height="16"></a> <a href="" class="rsce_list_toolbar_new" onclick="rsceNewElementAfter(this);return false;" title="" data-rsce-title="Neues Element erstellen"><img src="system/themes/flexible/icons/new.svg" alt="" width="16" height="16"></a> </div>`

Please change it to this (filled ALT attributes):
`<div class="rsce_list_toolbar"><a href="" class="rsce_list_toolbar_up" onclick="rsceMoveElement(this, -1);return false;" title="" data-rsce-title="Eine Position nach oben verschieben"><img src="system/themes/flexible/icons/up.svg" alt="Eine Position nach oben verschieben" width="13" height="16"></a> <a href="" class="rsce_list_toolbar_down" onclick="rsceMoveElement(this, 1);return false;" title="" data-rsce-title="Eine Position nach unten verschieben"><img src="system/themes/flexible/icons/down.svg" alt="Eine Position nach unten verschieben" width="13" height="16"></a> <img src="system/themes/flexible/icons/drag.svg" alt="" class="drag-handle rsce_list_toolbar_drag" title="" width="16" height="16"> <a href="" class="rsce_list_toolbar_delete" onclick="rsceDeleteElement(this);return false;" title="" data-rsce-title="Element löschen"><img src="system/themes/flexible/icons/delete.svg" alt="Element löschen" width="16" height="16"></a> <a href="" class="rsce_list_toolbar_new" onclick="rsceNewElementAfter(this);return false;" title="" data-rsce-title="Neues Element erstellen"><img src="system/themes/flexible/icons/new.svg" alt="Neues Element erstellen" width="16" height="16"></a> </div>`

Without this, it is very hard for screen reader users to understand and use the icons. 

Thank you for your help!

**Comment by ausi** [comment]
Fixed. Thank you for reporting this issue.
