### ISSUE TITLE
bug with pageTree field within list

### ISSUE THREAD

**Issue by fritzmg** [madeyourday/contao-rocksolid-custom-elements#85]
If you have a `pageTree` field within a `list`, selecting the page of the additional items will not work.

## Reproduction

1. Use an RSCE element with a config like [1].
2. Create the new RSCE element.
3. Add a new list item and select a page.
4. Do __not__ save and add another list item and select a page.

The page selection will not work for the second item. Instead, the page selection of the first item will be changed to whatever you chose for the second item.

[1]
```php
<?php

return array(
    'label' => array('Test', ''),
    'types' => array('content'),
    'contentCategory' => 'includes',
    'standardFields' => array('cssID'),
    'wrapper' => array('type' => 'none'),
    'fields' => array(
        'pages' => array(
            'label' => array('Pages', ''),
            'elementLabel' => '%s. Box',
            'inputType' => 'list',
            'minItems' => 0,
            'maxItems' => 3,
            'fields' => array(
                'page' => array(
                    'label' => array('Page','Choose a page.'),
                    'inputType'  => 'pageTree',
                    'foreignKey' => 'tl_page.title',
                    'eval'       => array('fieldType'=>'radio')
                )
            )
        )
    )
);
```
As a workaround you currently have to save the element, before adding a new list item.

**Comment by ausi** [comment]
I was not able to reproduce this issue. Are you using the latest version of Contao (4.4.2) and of the extension (2.0.3)?

**Comment by ausi** [comment]
@fritzmg any updates on this issue?

**Comment by fritzmg** [comment]
Not yet, I was on vacation. I'll close in the mean time and reopen if I can reproduce it again :)

**Comment by fritzmg** [comment]
I was unable to reproduce this in the original site with the newest versions of Contao 4.4 and RSCE.
