### ISSUE TITLE
alt-attributes are not used from file database for image standard field

### ISSUE THREAD

**Issue by polyneo-florian** [madeyourday/contao-rocksolid-custom-elements#86]
I worked the first time with the Custom Elements extension (really great extension, thank you!) and use it currently in Contao 4.4.2.

I added the standard field "image" to my custom element and generate the image in the frontend template with the following (to get repsonsive images, etc.):
`<?php $this->insert('image', $this->arrData); ?>`

When I enter meta data in the file manager (e.g. alt-attributes), it is not used for the image that is generated by the frontend template at all.
Using the "override meta data" checkbox and entering the meta tags like the alt-attributes for each image manually, it works without any problem.
But entering the data for several hundred files across the whole website shouldn't be the meaning of it, right? ;)

Did I do something wrong? Or might there be a problem with the standard image field?
Thanks in advance, any help or advice is appreciated! :+1:

**Comment by ausi** [comment]
Thank you for reporting the issue. This will be fixed with the next release.
