### ISSUE TITLE
'maxItems' doesnt work

### ISSUE THREAD

**Issue by sebssch** [madeyourday/contao-rocksolid-custom-elements#88]
Trotz 'maxItems' => 2 in der config Datei besteht die Möglichkeit, über das '+' weitere Elemente hinzuzufügen. Der Button 'neues Element' verschwindet jedoch. 

![screenshot-2](https://user-images.githubusercontent.com/18069290/31943869-61c9a5ea-b8ca-11e7-85cc-a3392b9b0d9f.png)

![screenshot-1](https://user-images.githubusercontent.com/18069290/31943870-61e81a66-b8ca-11e7-8605-f5cdc942dda7.png)

**Comment by ausi** [comment]
Thank you for submitting this issue!

Fixed in [version 2.2.1](https://github.com/madeyourday/contao-rocksolid-custom-elements/releases/tag/v2.2.1).

**Comment by sebssch** [comment]
Thank you
