### ISSUE TITLE
Cotnao 4.x Not able to pass contao/install if tables are not created

### ISSUE THREAD

**Issue by dmolineus** [madeyourday/contao-rocksolid-custom-elements#93]
If you open the contao install tool after installing the rocksolid custom elements without creating the database before (e.g. using a custom project composer.json) following error occurs:

![4b1f22d5-0204-4cda-b1ea-023c0fc40bfb](https://user-images.githubusercontent.com/1186266/35860666-23c7ceb6-0b45-11e8-972e-94525c73ee3f.png)

**Comment by ausi** [comment]
I was not able to reproduce that.

There is already a check to skip initializing for Install-Tool Requests in https://github.com/madeyourday/contao-rocksolid-custom-elements/blob/b0aa71a302dd351bd81d5f24f0630835dc49626b/src/CustomElements.php#L1088-L1104

Can you debug why this check doesn’t work in your installation? Which Version of Contao are you using?

**Comment by dmolineus** [comment]
After creating the issue (and temporary removing custom elements) I still had other issues in that installation (Contao 4.4.13). It seemed that an extension was triggering `\BackendUser::authenticate` during the contao framework initialization in the install tool. I guess that the error occured on the login route instead of the install route. 

However, I'm not able to do any further investigation before next week. I close this ticket and if the issue is really part of rsce I'll report it. Sorry for the trouble.
