### ISSUE TITLE
Feature: Contao 4.x: Links to News, Events, FAQs etc.

### ISSUE THREAD

**Issue by jankout** [madeyourday/contao-rocksolid-custom-elements#96]
Hello, 

at the moment it isn't possible to set the url to the news, events, faqs although it's possible with the new and very useful feature since Conta 4.3 (I guess). Could you implement it, please? Thank you.

**Comment by fkaminski** [comment]
Mit 
`'url' => array( 
    'inputType' => 'standardField', 
    'eval' => array( 
      'dcaPicker'=>true, 'mandatory'=>true, 
    ), 
`
erhalte ich entsprechende Auswahlen im BE. Allerdings wüßte ich gerne wie ich z.B. die Auwahl auf "News" o. "Events" beschränken könnte ...

**Comment by fkaminski** [comment]
Laut [Beitrag](https://github.com/contao/core-bundle/issues/924#issuecomment-315081990)
dann einschränken auf News mit z.B.
`'eval' => array(  
      'dcaPicker' => array ('providers' => array('newsPicker') ) 
    ),  `

(with help from Contao forum and @fritzmg)

**Comment by ausi** [comment]
Implemented in Version 2.2.8

**Comment by jankout** [comment]
> Implemented in Version 2.2.8

Vielen lieben Dank. Thank you very much.
