### ISSUE TITLE
Wrapper Types

### ISSUE THREAD

**Issue by rustykowski** [madeyourday/contao-rocksolid-custom-elements#98]
Was ist mit der Option wrapper -> single gemeint? Wofür ist das gedacht?

`'wrapper' => array(
        'type' => 'single',
    )`

**Comment by ausi** [comment]
Damit wird das Element in `$GLOBALS['TL_WRAPPERS']['single']` registriert. Ein Beispiel dafür ist das Inhaltselement „Akkordeon (Einzelelement)“.
